In [1]:
# Assisted by WCA@IBM
# Latest GenAI contribution: ibm/granite-20b-code-instruct-v2
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the input data (X) and target (y)
X = [[1], [2], [3], [4]]
y = [1, 2, 3, 4]

# Create a linear regression model
model = LinearRegression()

# Fit the model to the data
model.fit(X, y)

# Make predictions using the model
predictions = model.predict([[5]])

# Print the predictions
print(predictions)

[5.]

In [8]:
# Assisted by WCA@IBM
# Latest GenAI contribution: ibm/granite-20b-code-instruct-v2
import pandas as pd

# Specify the URL of the CSV file in the GitHub repository
url = "https://raw.githubusercontent.com/WilHoge/NYC-taxi-viz/master/data/taxi-av100000.csv"

# Read the CSV data into a pandas DataFrame
df = pd.read_csv(url)

# Print the first few rows of the DataFrame
df.head()

,Unnamed: 0,Vendor,pickup.datetime,dropoff.datetime,passenger.count,trip.time,trip.distance,pickup.longitude,pickup.latitude,dropoff.longitude,...,Day,Hour,Temperature,Precipitation,pickup.date,weekday,weekend,rain,fare.per.mile,speed
0,1,VTS,2013-04-15 20:30:00.0,2013-04-15 20:39:00.0,1,540,1.63,-73.983177,40.756702,-73.977386,...,15,20,9.4,0.0,2013-04-15,Monday,no,no,5.214724,10.866667
1,2,VTS,2013-04-15 23:55:00.0,2013-04-15 23:59:00.0,2,240,1.33,-73.949974,40.776089,-73.964874,...,15,23,8.9,0.0,2013-04-15,Monday,no,no,4.511278,19.950000
2,3,VTS,2013-04-16 07:59:00.0,2013-04-16 08:14:00.0,3,900,2.86,-73.966537,40.794365,-73.982155,...,16,7,9.4,0.0,2013-04-16,Tuesday,no,no,4.370629,11.440000
3,4,VTS,2013-04-04 13:41:00.0,2013-04-04 13:46:00.0,1,300,0.57,-73.977150,40.751736,-73.972336,...,4,13,8.3,0.0,2013-04-04,Thursday,no,no,8.771930,6.840000
4,5,VTS,2013-04-04 14:12:00.0,2013-04-04 14:35:00.0,1,1380,9.58,-73.982307,40.751774,-73.865692,...,4,14,9.4,0.0,2013-04-04,Thursday,no,no,3.027140,24.991304

In [16]:
# Assisted by WCA@IBM
# Latest GenAI contribution: ibm/granite-20b-code-instruct-v2
import pandas as pd
import os

# Upload the file to your Watson Studio project
from ibm_watson_studio_lib import access_project_or_space
credentials_dic={"project_id":os.getenv("PROJECT_ID"), "token":os.getenv("USER_ACCESS_TOKEN")}
wslib = access_project_or_space(params=credentials_dic)

wslib.save_data("my_asset_name.csv", df.to_csv(index=False).encode())

{'name': 'my_asset_name.csv',
 'asset_type': 'data_asset',
 'asset_id': 'data_asset.myassetnamecsv',
 'attachment_id': '802226cb-7d08-4c79-b5b1-80e961701425',
 'filepath': 'my_asset_name.csv',
 'data_size': None,
 'mime': 'text/csv',
 'summary': ['created file', 'created data asset', 'created attachment']}